CLASS zcl_test_umlaut DEFINITION
  PUBLIC
  INHERITING FROM cl_demo_classrun
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS main REDEFINITION.

  PROTECTED SECTION.

  PRIVATE SECTION.
ENDCLASS.


CLASS zcl_test_umlaut IMPLEMENTATION.
  METHOD main.
  ENDMETHOD.
ENDCLASS.
